### ISSUE TITLE
Please provide a proper license tag in the Cabal file

### ISSUE THREAD

**Issue by peti** [mongodb-haskell/bson#11]
My understanding is that `APL-2.0` would be the correct choice.

**Comment by VictorDenisov** [comment]
Accordingly to https://www.haskell.org/cabal/users-guide/developing-packages.html#package-properties

license field should be a constant of License type: https://www.haskell.org/cabal/release/cabal-latest/doc/API/Cabal/Distribution-License.html#t:License

License type doesn't have APL-2.0 constructor. So, it correctly specifies OtherLicense in the license field and license-file refers to LICENSE file, which describes Apache 2 license.

**Comment by peti** [comment]
You are right. It's `Apache-2.0`, not `APL-2.0`.

**Comment by VictorDenisov** [comment]
Hm. I thought I looked for Apache, but I missed it.  I'll need to figure out how to specify version. I'll do it.

**Comment by VictorDenisov** [comment]
Fixed. Thanks for posting the ticket.
